### ISSUE TITLE
Something's wrong with PythonKernel

### ISSUE THREAD

**Issue by benvanwerkhoven** [KernelTuner/kernel_tuner#119]
Using the PythonKernel in a test case gave some strange issues, and replacing these with calls to run_kernel solved the problem. So there is a bug somewhere in the PythonKernel implementation. Either with how arguments are copied into the kernel or with the way results are copied back from the GPU to the host.

**Comment by wjp** [comment]
One error I'm seeing when experimenting is caused by the pycuda device context handling. If you currently create a PythonKernel object (with lang=CUDA), it will create and activate a context via pycuda in the constructor. The destructor of this object will get called at a more or less random time and deactivate whatever context is active at that time.

I'm starting to think we should entirely change the way our pycuda backend manages contexts if we want to be able to "naturally" encapsulate kernels (and their corresponding DeviceInterface and cuda context) in PythonKernel objects: the current pycuda backend implicitly assumes that nothing else is touching the GPU's active context, which is somewhat okay if we can manage this inside a single tune_kernel or run_kernel call, but isn't realistic if a PythonKernel can have an effectively arbitrary lifetime.

**Comment by wjp** [comment]
P.S. "entirely changing" the pycuda backend's context handling is probably not all that hard. Just need to carefully go over it and see where the context needs to be explicitly handled, and make sure any push() and pop() calls (if still needed) are paired so that they can't disrupt other code (or other DeviceInterface/PythonKernel instances).

**Comment by benvanwerkhoven** [comment]
I noticed I never closed this issue. Many thanks @wjp for fixing this!
