### ISSUE TITLE
Special memories only work with PyCUDA backend

### ISSUE THREAD

**Issue by isazi** [KernelTuner/kernel_tuner#210]
The functions:
- `copy_shared_memory_args`
- `copy_constant_memory_args`
- `copy_texture_memory_args`
In `core.py` check if `self.lang == "CUDA"`, and not work with e.g. CuPy or other backends that implement the functionality.

Moreover, this is only checked if using `run_kernel` and not `tune_kernel`. I am waiting for some comments before fixing it, as I may have overlooked something.

**Comment by benvanwerkhoven** [comment]
I do know that constant memory works with the CuPy backend. But now that the number of backends is expanding, a table with feature completeness per backend would be nice to have.

In the meantime, I was also inspecting the code and I think you're onto something interesting here. There is some very old code in core.py that I've quoted below. This indeed includes the if's for ``lang == "CUDA"``.

The code in `compile_and_benchmark` is however not running into any issues since it skips these high-level variants and immediately calls the `copy_constant_memory_args` etc on `self.dev` instead of `self`. Basically, I think that the functions on these lines:
https://github.com/KernelTuner/kernel_tuner/blob/b3ff4cdecb12655009b356e3b1840e25b1dd1421/kernel_tuner/core.py#L497-L516 
are actually not used at all and could be removed.

**Comment by benvanwerkhoven** [comment]
I've just made some extensions to the documentation on backends see pull request #213

**Comment by benvanwerkhoven** [comment]
It would appear that run_kernel maybe does use these methods. Will look into this soon.

**Comment by isazi** [comment]
I will fix this tomorrow. And base my "patch" on the mega pull-request from @fjwillemsen (unless that is merged into master already today or tomorrow).

**Comment by fjwillemsen** [comment]
The plan is indeed that #214 will be merged today or tomorrow, directly after Stein's pull request #189. 
I'll notify you by posting in this thread once they have been merged.

**Comment by isazi** [comment]
Perfect, then I will just fix this issue on master after your merge, and avoid the conflicts :)

**Comment by fjwillemsen** [comment]
Both #189 and #214 have been merged!

**Comment by isazi** [comment]
Great, I will do this today. Will reach to you if something is not clear about the new development environment.

**Comment by isazi** [comment]
The issue was already fixed by @MiloLurati in the HIP backend 5 months ago. So I removed the three functions listed at the top of this issue as they are not used anywhere else.

**Comment by isazi** [comment]
This should be fixed for now.
